### ISSUE TITLE
Can't build: undefined: v8go.Context

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#348]
When doing a fresh build on Ubuntu 24.04, running `go build` throws the following as discussed previously (https://github.com/rogchap/v8go/issues/38):
```
# github.com/plentico/plenti/cmd/build
cmd/build/client.go:24:18: undefined: v8go.Context
cmd/build/client.go:47:14: undefined: v8go.NewContext
cmd/build/client.go:54:16: undefined: v8go.NewContext
cmd/build/client.go:213:107: undefined: v8go.Context
cmd/build/compile.go:45:30: undefined: v8go.Context
```

First, make sure you enable CGO when running your build, which is required to V8Go: `CGO_ENABLED=1 go build`

That might still throw:
```
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
```

So make sure to install dependencies: `sudo apt-get install build-essential`

Then you should be able to `CGO_ENABLED=1 go build` successfully :heavy_check_mark:
